# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4e30038e0eb05da5345af15472eb8388dab6d288858083f80f68b878e6b7518c45a3fdec68173accaba842c858fa0f34c41175ae4323a14d3de568a13d226a22

test:
  secret_key_base: 824f2fe8df4590fdd654a2437692f3af9f3b4c95da23ea12535017d055d998e01694fd5a93ba8e0f9edbdeade99644c48766404f8348d1cd062cf33fb36f1c3c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
